language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: npm release
      if: branch = master
      before_deploy:
      - npm run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
